/**
 * SIMPLY CONNECT — Agent Performance Dashboard
 * Google Apps Script API backend
 * ------------------------------------------------------------
 * WHAT THIS DOES
 * This script turns your Google Sheet ("Calls Data" + "sales Data" tabs)
 * into a JSON API that the dashboard (index.html) reads from.
 * Every time the dashboard loads or you hit "Refresh", it calls this
 * script's web app URL and gets back the latest numbers — so as long as
 * your sheet keeps getting new rows every day, the dashboard updates
 * itself with zero extra work.
 *
 * SETUP (also in README.md)
 * 1. Open your Google Sheet → Extensions → Apps Script.
 * 2. Delete any starter code and paste this whole file in.
 * 3. Update the CONFIG block below (sheet names + optional secret key).
 * 4. Click Deploy → New deployment → type: Web app.
 *      - Execute as: Me
 *      - Who has access: Anyone
 * 5. Copy the Web app URL it gives you — paste it into the dashboard's
 *    "API Setup" tab (or into js/config.js before you deploy to Vercel).
 * 6. Re-deploy (Deploy → Manage deployments → Edit → New version) any
 *    time you edit this script.
 * ------------------------------------------------------------
 */

// ============================= CONFIG =============================
const CONFIG = {
  CALLS_SHEET_NAME: 'Calls Data',
  SALES_SHEET_NAME: 'sales Data',

  // Optional shared secret. Leave blank to disable. If set, the
  // dashboard must send ?key=YOUR_SECRET in the request URL, otherwise
  // the API refuses to respond. This is not bank-grade security (the
  // key is visible in the browser), but it stops random strangers who
  // find the URL from scraping your data.
  SHARED_SECRET: '',

  // How many days of history to return by default when the dashboard
  // doesn't ask for a specific range. Keeps the response fast even
  // once the sheet has 100,000+ rows.
  DEFAULT_DAYS: 90,

  // Hard ceiling — even if someone requests a huge range, we cap it
  // so the Apps Script execution doesn't time out.
  MAX_DAYS: 730,

  // How long (seconds) a response is cached before we re-read the
  // sheet. 300 = 5 minutes. Set to 0 to always read fresh.
  CACHE_SECONDS: 300,

  // gRPCampaign Number / Call Center Name values that should be
  // treated as the same campaign, e.g. "Group 44" call center rows
  // and "Group 44 Sales" call center rows both belong to "Group 44".
  // The script strips trailing words like "Sales"/"CS"/"Opp" automatically
  // (see normalizeCampaign_), so you usually don't need to edit this.
};

// Column names we DELETE from the sales rows before they ever leave
// this script. This protects your customers' personal information —
// the web app URL is public-facing, so we never want names, emails,
// phone numbers, addresses, account numbers or PINs to leave the
// spreadsheet. Only the fields the dashboard actually charts survive.
const SALES_PII_COLUMNS_TO_DROP = [
  'Customer Name', 'Customer E-mail', 'Phone number', 'Alternate phone number',
  'Customer Address', 'Zip code', 'Order Confirmation Number (OCN)',
  'Work Order Number', 'Account Number', 'Comments', 'Screenshot',
  'Account Pin', 'Account Security Question', 'Timestamp'
];

// The sales columns we DO keep + send to the dashboard (in addition to
// whatever survives the drop-list above). Keeping an explicit allow-list
// is the safest approach: if a new sensitive column gets added to the
// sheet later, it will NOT be exposed unless you add it here.
const SALES_FIELDS_ALLOWED = [
  'Date', 'gRPCampaign Number', 'Agent Name', 'State', 'Provider', 'Services',
  "RGU's", 'Installation Type', 'Closer Name', 'Sales Call/Non Sales Call',
  'Lead Generated by (If Any)', 'Current Provider', 'Team',
  'Call Received from Queue Name', 'Total Points'
];

const CALLS_FIELDS_ALLOWED = [
  'Call Center Name', 'Date', 'Time Frame', 'Agent Name', 'Call Result',
  'Wait Time', 'Talk Time', 'Hold Time', 'Wrap Up Time', 'Disposition Codes'
];

// ============================ WEB ENTRY =============================

function doGet(e) {
  try {
    const params = (e && e.parameter) || {};

    if (CONFIG.SHARED_SECRET && params.key !== CONFIG.SHARED_SECRET) {
      return jsonOutput_({ error: 'Unauthorized. Missing or invalid ?key=' }, 401);
    }

    const days = clamp_(parseInt(params.days, 10) || CONFIG.DEFAULT_DAYS, 1, CONFIG.MAX_DAYS);
    const cacheKey = 'dash_v1_' + days;

    if (CONFIG.CACHE_SECONDS > 0) {
      const cached = CacheService.getScriptCache().get(cacheKey);
      if (cached) {
        return jsonOutput_(JSON.parse(cached), 200);
      }
    }

    const payload = buildPayload_(days);

    if (CONFIG.CACHE_SECONDS > 0) {
      try {
        // CacheService has a 100KB per-key limit — large payloads simply
        // won't be cached, which is fine, they'll just recompute each call.
        CacheService.getScriptCache().put(cacheKey, JSON.stringify(payload), CONFIG.CACHE_SECONDS);
      } catch (cacheErr) {
        // Payload too big to cache — not fatal, continue without caching.
      }
    }

    return jsonOutput_(payload, 200);
  } catch (err) {
    return jsonOutput_({ error: String(err) }, 500);
  }
}

function jsonOutput_(obj, statusCode) {
  const out = ContentService.createTextOutput(JSON.stringify(obj));
  out.setMimeType(ContentService.MimeType.JSON);
  return out;
}

// ============================ CORE LOGIC =============================

function buildPayload_(days) {
  const ss = SpreadsheetApp.getActiveSpreadsheet();
  const cutoff = new Date();
  cutoff.setDate(cutoff.getDate() - days);
  cutoff.setHours(0, 0, 0, 0);

  const calls = readSheetAsObjects_(ss, CONFIG.CALLS_SHEET_NAME);
  const sales = readSheetAsObjects_(ss, CONFIG.SALES_SHEET_NAME);

  const callsOut = [];
  let lastCallDate = null;
  calls.forEach(function (row) {
    const d = toDate_(row['Date']);
    if (!d || d < cutoff) return;
    if (!lastCallDate || d > lastCallDate) lastCallDate = d;
    const rec = pickFields_(row, CALLS_FIELDS_ALLOWED);
    rec['Date'] = formatDate_(d);
    rec['Campaign'] = normalizeCampaign_(rec['Call Center Name']);
    rec['Wait Time'] = toSeconds_(row['Wait Time']);
    rec['Talk Time'] = toSeconds_(row['Talk Time']);
    rec['Hold Time'] = toSeconds_(row['Hold Time']);
    rec['Wrap Up Time'] = toSeconds_(row['Wrap Up Time']);
    rec['Hour'] = extractHour_(row['Call Answer Time'], row['Time Frame']);
    callsOut.push(rec);
  });

  const salesOut = [];
  let lastSaleDate = null;
  sales.forEach(function (row) {
    const d = toDate_(row['Date']);
    if (!d || d < cutoff) return;
    if (!lastSaleDate || d > lastSaleDate) lastSaleDate = d;
    const rec = pickFields_(row, SALES_FIELDS_ALLOWED);
    rec['Date'] = formatDate_(d);
    rec['Campaign'] = normalizeCampaign_(rec['gRPCampaign Number']);
    rec["RGU's"] = Number(row["RGU's"]) || 0;
    rec['Total Points'] = Number(row['Total Points']) || 0;
    salesOut.push(rec);
  });

  return {
    generatedAt: new Date().toISOString(),
    rangeDays: days,
    meta: {
      callsRows: callsOut.length,
      salesRows: salesOut.length,
      lastCallDate: lastCallDate ? formatDate_(lastCallDate) : null,
      lastSaleDate: lastSaleDate ? formatDate_(lastSaleDate) : null
    },
    calls: callsOut,
    sales: salesOut
  };
}

function readSheetAsObjects_(ss, sheetName) {
  const sheet = ss.getSheetByName(sheetName);
  if (!sheet) throw new Error('Sheet not found: ' + sheetName);
  const values = sheet.getDataRange().getValues();
  if (values.length < 2) return [];
  const headers = values[0];
  const rows = [];
  for (let i = 1; i < values.length; i++) {
    const row = values[i];
    // Skip fully blank rows
    if (row.join('') === '') continue;
    const obj = {};
    for (let c = 0; c < headers.length; c++) {
      if (!headers[c]) continue;
      obj[headers[c]] = row[c];
    }
    rows.push(obj);
  }
  return rows;
}

function pickFields_(row, allowList) {
  const out = {};
  allowList.forEach(function (key) {
    if (SALES_PII_COLUMNS_TO_DROP.indexOf(key) !== -1) return; // extra safety net
    if (Object.prototype.hasOwnProperty.call(row, key)) {
      out[key] = row[key];
    }
  });
  return out;
}

// ============================ HELPERS =============================

function toDate_(value) {
  if (value instanceof Date) return value;
  if (!value) return null;
  const d = new Date(value);
  return isNaN(d.getTime()) ? null : d;
}

function formatDate_(d) {
  return Utilities.formatDate(d, Session.getScriptTimeZone() || 'America/Chicago', 'yyyy-MM-dd');
}

function toSeconds_(value) {
  // Sheet stores times like 00:05:23 as a Date/time-of-day value.
  if (value instanceof Date) {
    return value.getHours() * 3600 + value.getMinutes() * 60 + value.getSeconds();
  }
  if (typeof value === 'number') {
    // Excel/Sheets time serials are a fraction of a day.
    return Math.round(value * 86400);
  }
  if (typeof value === 'string' && value.indexOf(':') !== -1) {
    const parts = value.split(':').map(Number);
    if (parts.length === 3) return parts[0] * 3600 + parts[1] * 60 + parts[2];
    if (parts.length === 2) return parts[0] * 60 + parts[1];
  }
  return 0;
}

function extractHour_(answerTimeValue, timeFrame) {
  if (answerTimeValue instanceof Date) return answerTimeValue.getHours();
  if (typeof answerTimeValue === 'string') {
    const m = answerTimeValue.trim().match(/^(\d{1,2}):/);
    if (m) return parseInt(m[1], 10);
  }
  if (typeof timeFrame === 'string') {
    const m = timeFrame.match(/^(\d{1,2})/);
    if (m) return parseInt(m[1], 10);
  }
  return null;
}

// Turns "Group 44 Sales", "Group 44 CS", "Group 44" all into "Group 44",
// so the Calls tab and the Sales tab can be joined on the same campaign
// name even though the call center naming is inconsistent.
function normalizeCampaign_(value) {
  if (!value) return 'Unassigned';
  const str = String(value).trim();
  const m = str.match(/^(Group\s*\d+)/i);
  if (m) return m[1].replace(/\s+/g, ' ');
  return str;
}

function clamp_(n, min, max) {
  return Math.max(min, Math.min(max, n));
}

/**
 * Run this once from the Apps Script editor (select function
 * "testPayload_" in the toolbar dropdown → Run) to sanity-check the
 * output in the execution log before you deploy.
 */
function testPayload_() {
  const payload = buildPayload_(CONFIG.DEFAULT_DAYS);
  Logger.log(JSON.stringify(payload).substring(0, 2000));
  Logger.log('Calls: %s, Sales: %s', payload.meta.callsRows, payload.meta.salesRows);
}
